version: '3.8'

services:
  playwright-tests:
    build: .
    container_name: blazedemo-playwright-tests
    volumes:
      # Mount test results and reports to host
      - ./test-results:/app/test-results
      - ./playwright-report:/app/playwright-report
      # Mount source code for live development (optional)
      - ./src:/app/src
      - ./tests:/app/tests
    environment:
      - CI=true
      - HEADLESS=true
      - NODE_ENV=test
    networks:
      - playwright-network
    command: npm test

  # Service for running tests in headed mode (with VNC)
  playwright-headed:
    build: .
    container_name: blazedemo-playwright-headed
    volumes:
      - ./test-results:/app/test-results
      - ./playwright-report:/app/playwright-report
      - ./src:/app/src
      - ./tests:/app/tests
    environment:
      - CI=false
      - HEADLESS=false
      - DISPLAY=:99
    ports:
      - "5900:5900"  # VNC port
      - "9323:9323"  # Report server port
    networks:
      - playwright-network
    command: npm run test:headed

  # Service for test report server
  report-server:
    build: .
    container_name: blazedemo-report-server
    volumes:
      - ./playwright-report:/app/playwright-report
    ports:
      - "9323:9323"
    networks:
      - playwright-network
    command: npx playwright show-report --host=0.0.0.0

  # Node.js development environment
  node-dev:
    image: node:18-alpine
    container_name: blazedemo-node-dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
      - "8080:8080"
    environment:
      - NODE_ENV=development
    networks:
      - playwright-network
    command: sh -c "npm install && npm run test:ui"

networks:
  playwright-network:
    driver: bridge

volumes:
  node_modules:
